### ISSUE TITLE
Visualize the output of model on image

### ISSUE THREAD

**Issue by Alaa-Salah-Younes** [colindecourt/record#4]
Hi , kindly let me know if there is away to visualize the output on model on image, or there are any kind of visualization that can be done in evaluation stage

**Comment by colindecourt** [comment]
Hi, 
I don't provide the script to visualize the output of the model in evaluation stage. However, you can use the functions available in the following file: https://github.com/colindecourt/record/blob/main/utils/vizualization.py to show predictions. 
Kind regards,
Colin
